/**
 * Expo Config Plugin: withAndroidReleaseBuild
 *
 * Owns the two parts of `android/app/build.gradle`'s `release` buildType that
 * `expo-build-properties` cannot express. Everything it CAN express (ABIs via
 * `buildArchs`, proguard rules via `extraProguardRules`, minify/shrink/SDK
 * levels) stays in `app.config.js` — do not duplicate those here.
 *
 * `android/` is gitignored and regenerated by `expo prebuild`, so these edits
 * have to live in a plugin or they are lost on the next prebuild.
 *
 * 1. R8 optimization passes
 *    Expo generates `getDefaultProguardFile("proguard-android.txt")`, whose
 *    only meaningful line is `-dontoptimize`. Swapping to the `-optimize`
 *    variant drops that and adds `-allowaccessmodification`, which is what lets
 *    R8 inline and merge classes. Measured on this app: dex 22,814,960 ->
 *    15,290,636 bytes uncompressed (-33%), 4 dex files -> 2.
 *
 * 2. Release signing
 *    Expo generates `signingConfig signingConfigs.debug` for release, and Play
 *    rejects a debug-signed AAB. The real credentials are read from Gradle
 *    properties (set in the developer's `~/.gradle/gradle.properties` or CI
 *    secrets) so nothing secret ever lands in the repo. When those properties
 *    are absent the build falls back to the debug keystore, so a contributor
 *    without the keystore can still build.
 *
 *    The certificate MUST be the shared Oxy ecosystem one: the manifest sets
 *    `android:sharedUserId="so.oxy.shared"` (see withSharedUserId) and Android
 *    requires every app sharing that UID to be signed with the SAME
 *    certificate. Signing Mention with an app-specific key would break
 *    "sign in once, use everywhere" against Commons/Allo/Homiio.
 */

const { withAppBuildGradle } = require('expo/config-plugins');

/** Gradle property names holding the release signing material. */
const STORE_FILE = 'OXY_UPLOAD_STORE_FILE';
const STORE_PASSWORD = 'OXY_UPLOAD_STORE_PASSWORD';
const KEY_ALIAS = 'OXY_UPLOAD_KEY_ALIAS';
const KEY_PASSWORD = 'OXY_UPLOAD_KEY_PASSWORD';

const DEFAULT_PROGUARD = 'getDefaultProguardFile("proguard-android.txt")';
const OPTIMIZED_PROGUARD = 'getDefaultProguardFile("proguard-android-optimize.txt")';

const DEBUG_SIGNING_CONFIG = 'signingConfig signingConfigs.debug';
const CONDITIONAL_SIGNING_CONFIG =
  `signingConfig project.hasProperty('${STORE_FILE}') ? signingConfigs.release : signingConfigs.debug`;

const RELEASE_SIGNING_CONFIG = `        release {
            // Populated only when the Oxy release keystore properties are
            // available; otherwise this config stays empty and the release
            // buildType falls back to signingConfigs.debug below.
            if (project.hasProperty('${STORE_FILE}')) {
                storeFile file(project.property('${STORE_FILE}'))
                storePassword project.property('${STORE_PASSWORD}')
                keyAlias project.property('${KEY_ALIAS}')
                keyPassword project.property('${KEY_PASSWORD}')
            }
        }
`;

function useOptimizedProguardFile(contents) {
  if (contents.includes(OPTIMIZED_PROGUARD)) return contents;
  if (!contents.includes(DEFAULT_PROGUARD)) {
    throw new Error(
      `[withAndroidReleaseBuild] Could not find ${DEFAULT_PROGUARD} in app/build.gradle. ` +
        'The Expo template changed — update this plugin instead of editing android/ by hand.',
    );
  }
  return contents.replace(DEFAULT_PROGUARD, OPTIMIZED_PROGUARD);
}

function addReleaseSigningConfig(contents) {
  if (contents.includes(CONDITIONAL_SIGNING_CONFIG)) return contents;

  // Declare signingConfigs.release immediately after the generated debug entry.
  const debugSigningBlock = /(signingConfigs\s*\{\s*\n\s*debug\s*\{[\s\S]*?\n\s{8}\}\n)/;
  if (!debugSigningBlock.test(contents)) {
    throw new Error(
      '[withAndroidReleaseBuild] Could not find the generated signingConfigs.debug block in ' +
        'app/build.gradle. The Expo template changed — update this plugin.',
    );
  }
  let next = contents.replace(debugSigningBlock, `$1${RELEASE_SIGNING_CONFIG}`);

  // Point the release buildType at it. The debug buildType also contains
  // `signingConfig signingConfigs.debug`, so only replace the occurrence that
  // follows the `release {` marker.
  const releaseBuildType = next.indexOf('release {', next.indexOf('buildTypes'));
  if (releaseBuildType === -1) {
    throw new Error(
      '[withAndroidReleaseBuild] Could not find the release buildType in app/build.gradle.',
    );
  }
  const target = next.indexOf(DEBUG_SIGNING_CONFIG, releaseBuildType);
  if (target === -1) {
    throw new Error(
      '[withAndroidReleaseBuild] Could not find the release buildType signingConfig line.',
    );
  }
  return (
    next.slice(0, target) +
    CONDITIONAL_SIGNING_CONFIG +
    next.slice(target + DEBUG_SIGNING_CONFIG.length)
  );
}

module.exports = function withAndroidReleaseBuild(config) {
  return withAppBuildGradle(config, (config) => {
    if (config.modResults.language !== 'groovy') {
      throw new Error(
        `[withAndroidReleaseBuild] Expected a Groovy app/build.gradle, got ${config.modResults.language}.`,
      );
    }
    config.modResults.contents = addReleaseSigningConfig(
      useOptimizedProguardFile(config.modResults.contents),
    );
    return config;
  });
};
