import { requireOptionalNativeModule, type NativeModule } from 'expo';

/**
 * JS side of the local `MentionWidgets` Expo module — Mention's Android
 * home-screen widgets.
 *
 * The module is **Android-only and native-only**: widgets are a platform
 * surface with no iOS or web equivalent (iOS has WidgetKit, a different
 * framework in a different language), and because `android/` is generated by
 * CNG it is present only in builds made after it landed. So every export here
 * has to answer for a MISSING module rather than only a missing capability,
 * which is why `requireOptionalNativeModule` is used and its `null` handled once
 * here instead of at each call site.
 *
 * The surface is one function on purpose. A widget runs outside the app process,
 * so each one owns its data end to end natively — fetch, cache, render, deep
 * link — and anything mirrored here would be a second implementation of that
 * path. What is genuinely JS-side is the one fact only the running app knows:
 * that the content it is displaying has just changed. See `trendsWidgetSync.ts`
 * for when acting on that is worth a fetch.
 */

// `declare class`, not an interface: `NativeModule` is exported as the
// CONSTRUCTOR type, so only a class heritage clause yields the instance side.
// This is the shape create-expo-module generates.
declare class MentionWidgetsNativeModule extends NativeModule {
  /**
   * Enqueue an immediate refresh of the trends widget. Resolves once the work
   * is queued, not once it has run.
   */
  refreshTrends(): Promise<void>;
}

const nativeModule = requireOptionalNativeModule<MentionWidgetsNativeModule>('MentionWidgets');

/** Whether this build can host home-screen widgets at all. */
export const areHomeScreenWidgetsAvailable = nativeModule !== null;

/**
 * Ask the trends widget to fetch now.
 *
 * A no-op where the module is absent, and a no-op natively when no trends
 * widget is on the home screen — so callers never have to check either.
 */
export function refreshTrendsWidget(): Promise<void> {
  return nativeModule?.refreshTrends() ?? Promise.resolve();
}
