-- `post_media` carries a copy of `posts.created_at`, so ONE index can answer the
-- global Videos lane's whole question: video media of this orientation, newest
-- first.
--
-- WHY: the media filters live on `post_media` and the timestamp lives on `posts`,
-- and an index cannot span two tables. So the lane's chronological scan drove
-- from `posts` and probed `post_media` once per candidate row, and the cost was
-- bounded by how far down the chronological order it had to walk rather than by
-- the page. What makes that walk long is the lane's own seen set: those ids are
-- the posts it just showed, so they sit at the HEAD of the order and every one of
-- them has to be stepped over. Measured here on 275,000 posts (39,285 of them
-- video, 86,428 `post_media` rows), page of 60:
--
--   seen ids     posts scanned     buffers
--   0            1,420             4,753
--   250          2,863             9,428
--   1,000        7,494            32,459     <- the cap, i.e. an ordinary scroll
--
-- With this column and index the same page walks 398 media rows and 1,995
-- buffers, in 1.3-2.4 ms against 15.1-26.5 ms. The ratio is not the point: the
-- scan now stops at the page, so it stops growing with the corpus.
--
-- Not a general licence to denormalise. `posts.created_at` is written once by an
-- insert default and never updated — 35 `update(posts)` sites and not one sets it
-- — so there is no update path for a copy to miss. The single writer
-- (`insertChildRows`) reads the value back out of `posts` in the same statement
-- rather than accepting one from its caller, so a caller cannot pass a value that
-- disagrees, and `mediaChronoSync.test.ts` asserts the agreement rather than
-- trusting it. A column whose source DID change under it would need a trigger or
-- a generated column, and neither is available across tables. This is the same
-- argument `0021` makes for `post_authorships.post_created_at`, and deliberately
-- the same shape.
--
-- NULLABLE, deliberately, for `0021`'s reason: a `NOT NULL` column with no
-- default cannot be added to a populated table without rewriting it under an
-- ACCESS EXCLUSIVE lock, and the backfill below cannot run before the column
-- exists.
--
-- WHAT A NULL COSTS, and why it cannot lose a post. The three statements below
-- run in ONE transaction, so no row is NULL when this commits. The window that
-- can still produce one is the DEPLOY: between this landing and the new code
-- serving, a task running the old image inserts media rows without the column.
-- Such a row is not dropped from the lane — the scan JOINs on `post_id` and only
-- ORDERS on this column, and `desc nulls last` puts it at the BOTTOM of the lane.
-- So the symptom is a new video appearing last instead of first, which is visible
-- and self-describing, and the repair is to re-run the UPDATE below (it is
-- idempotent: `IS DISTINCT FROM` makes a second run a no-op). The alternative —
-- `NOT NULL` — would have turned that same window into failed writes on a live
-- image, which is the worse trade.
--
-- NOT ONLINE, matching `0003`, `0004`, `0021`, `0022` and `0028`: `CREATE INDEX
-- CONCURRENTLY` cannot run inside the migrator's transaction.
--
-- WHAT IT BLOCKS, and it is more than writes. The three statements run in ONE
-- transaction, so the ACCESS EXCLUSIVE lock `ALTER TABLE` takes is held until
-- COMMIT — not just for the catalogue change. ACCESS EXCLUSIVE conflicts with
-- every other lock mode, so for the whole run `post_media` is unavailable to
-- READS as well as writes. Verified rather than reasoned: with an
-- `ALTER TABLE ADD COLUMN` held open in one session, `select count(*) from
-- post_media` in another hits its `statement_timeout`, while the same query on
-- `posts` returns immediately. Only this one table is affected — but federation
-- ingest writes to it continuously, and any request hydrating a post's media
-- reads it, so this is a brief hard stop on media rather than a background build.
--
-- COST, measured here, warm, on RAM-backed storage:
--
--   post_media rows    ADD COLUMN    UPDATE      CREATE INDEX   total (1 txn)
--   81,083 (48 MB)     0.5 ms        861 ms      51 ms          996 ms
--   405,415 (94 MB)    0.5 ms      5,165 ms     236 ms
--
-- `ADD COLUMN` is free — no default means no rewrite. The `UPDATE` is the whole
-- cost and it is roughly linear, ~12.7 us/row, because it rewrites every row.
--
-- WHAT THAT IMPLIES FOR PRODUCTION, and what it does not. Production held
-- 622,474 posts at the cutover count (`scripts/assertPostgresPopulated.ts`,
-- 2026-08-04) and 9,465 posts carrying a video media item a week earlier
-- (`utils/feedQueryBuilder.ts`). `post_media` is roughly one row per media item,
-- so on those figures it sits between the two rows measured above and the backfill
-- is seconds, not minutes. Two things that is NOT: it is not a measurement of
-- production, and the storage here is a RAM-backed tmpfs while production is RDS
-- on EBS, where a row-rewriting `UPDATE` is WAL-bound and slower. Treat the table
-- above as a floor and the shape as the transferable part.
--
-- If it turns out to matter, the recovery is the one `0028` names: split this into
-- the column plus a batched backfill outside the migrator, and build the index
-- concurrently.

ALTER TABLE "post_media" ADD COLUMN "post_created_at" timestamp with time zone;--> statement-breakpoint
UPDATE "post_media" m SET "post_created_at" = p."created_at" FROM "posts" p WHERE p."id" = m."post_id" AND m."post_created_at" IS DISTINCT FROM p."created_at";--> statement-breakpoint
CREATE INDEX "post_media_video_chrono_idx" ON "post_media" USING btree ("type","orientation","post_created_at" DESC NULLS LAST,"post_id" DESC NULLS LAST);
