import { requireOptionalNativeModule, type NativeModule } from 'expo';

/**
 * JS side of the local `MentionPipTransport` Expo module — next / previous
 * buttons inside the Android OS Picture-in-Picture window.
 *
 * The module is **Android-only and native-only**: it ships no iOS or web
 * implementation (AVKit exposes no way to add buttons to an `AVPlayer`-backed
 * PiP window, and browsers use `navigator.mediaSession` instead), and because
 * `android/` is generated by CNG it is present only in builds made after it
 * landed. Every export below therefore has to answer for a MISSING module, not
 * just a missing capability — which is why `requireOptionalNativeModule` is used
 * and its `null` is handled here once, rather than left to each caller. (The
 * failure mode being avoided is expo-video's own `isPictureInPictureSupported()`,
 * which THROWS in a browser because its web shim never defines the method.)
 */

export type PipTransportActionId = 'previous' | 'next';

export interface PipTransportAction {
  id: PipTransportActionId;
  /** Localized label; also what TalkBack announces. */
  title: string;
}

export interface PipTransportActionEvent {
  id: PipTransportActionId;
}

// A type alias, not an interface: `NativeModule`'s events map is constrained to
// `Record<string, ...>`, and only an alias carries the implicit index signature
// that satisfies it.
type PipTransportEvents = {
  onAction: (event: PipTransportActionEvent) => void;
};

// `declare class`, not an interface: `NativeModule` is exported as the
// CONSTRUCTOR type, so only a class heritage clause yields the instance side
// (`addListener` and friends). This is the shape create-expo-module generates.
declare class PipTransportNativeModule extends NativeModule<PipTransportEvents> {
  /** How many actions this device's PiP window shows; `0` where there is no PiP. */
  getMaxActions(): number;
  setActions(actions: readonly PipTransportAction[]): Promise<void>;
  clearActions(): Promise<void>;
  setAspectRatio(width: number, height: number): Promise<void>;
}

export type PipTransportSubscription = ReturnType<PipTransportNativeModule['addListener']>;

const nativeModule = requireOptionalNativeModule<PipTransportNativeModule>('MentionPipTransport');

/** Whether this build can put buttons in the OS window at all. */
export const isPipTransportAvailable = nativeModule !== null;

/**
 * The device's cap on PiP actions — three on most, but a runtime query, and `0`
 * both where the module is absent and where the device has no PiP.
 */
export function getMaxPipActions(): number {
  return nativeModule?.getMaxActions() ?? 0;
}

/** Publish the window's actions. Rejects if the activity cannot show them. */
export function setPipActions(actions: readonly PipTransportAction[]): Promise<void> {
  return nativeModule?.setActions(actions) ?? Promise.resolve();
}

/** Withdraw them again. */
export function clearPipActions(): Promise<void> {
  return nativeModule?.clearActions() ?? Promise.resolve();
}

/**
 * Give the OS window the video's shape, so a portrait video is not shown in a
 * landscape box.
 *
 * expo-video computes this once, in `VideoView.onVideoSourceLoaded`, from
 * `player.videoSize` — and never again, because its `VideoView` has no
 * `onVideoSizeChanged`. At source-load time ExoPlayer has usually not reported a
 * size yet, so the value is `0×0`, which is not a valid `Rational`; Android
 * rejects it and falls back to its own default, and that default is landscape.
 * On a reels screen that swaps sources with `replace`, even a correct first value
 * then goes stale for every video after it.
 *
 * So the caller passes the size it actually knows (`player.videoTrack.size`, or
 * the intrinsic dimensions the feed persists). Extreme ratios are clamped
 * natively to Android's own 1:2.39 … 2.39:1 limits rather than rejected — outside
 * that range `setAspectRatio` throws, and refusing a 1:3 crop would put it back in
 * the landscape window this exists to prevent.
 *
 * Resolves without doing anything where the module is absent (iOS, web, or a build
 * older than the module), like every other export here.
 */
export function setPipAspectRatio(width: number, height: number): Promise<void> {
  return nativeModule?.setAspectRatio(width, height) ?? Promise.resolve();
}

/**
 * Listen for a press. `null` where the module is absent — there is nothing to
 * unsubscribe from, and inventing a no-op subscription would only hide that.
 */
export function addPipActionListener(
  listener: (event: PipTransportActionEvent) => void,
): PipTransportSubscription | null {
  return nativeModule?.addListener('onAction', listener) ?? null;
}
