import { requireOptionalNativeModule, type NativeModule } from 'expo';

/**
 * JS side of the local `MentionPipTransport` Expo module — next / previous
 * buttons inside the Android OS Picture-in-Picture window.
 *
 * The module is **Android-only and native-only**: it ships no iOS or web
 * implementation (AVKit exposes no way to add buttons to an `AVPlayer`-backed
 * PiP window, and browsers use `navigator.mediaSession` instead), and because
 * `android/` is generated by CNG it is present only in builds made after it
 * landed. Every export below therefore has to answer for a MISSING module, not
 * just a missing capability — which is why `requireOptionalNativeModule` is used
 * and its `null` is handled here once, rather than left to each caller. (The
 * failure mode being avoided is expo-video's own `isPictureInPictureSupported()`,
 * which THROWS in a browser because its web shim never defines the method.)
 */

export type PipTransportActionId = 'previous' | 'next';

export interface PipTransportAction {
  id: PipTransportActionId;
  /** Localized label; also what TalkBack announces. */
  title: string;
}

export interface PipTransportActionEvent {
  id: PipTransportActionId;
}

// A type alias, not an interface: `NativeModule`'s events map is constrained to
// `Record<string, ...>`, and only an alias carries the implicit index signature
// that satisfies it.
type PipTransportEvents = {
  onAction: (event: PipTransportActionEvent) => void;
};

// `declare class`, not an interface: `NativeModule` is exported as the
// CONSTRUCTOR type, so only a class heritage clause yields the instance side
// (`addListener` and friends). This is the shape create-expo-module generates.
declare class PipTransportNativeModule extends NativeModule<PipTransportEvents> {
  /** How many actions this device's PiP window shows; `0` where there is no PiP. */
  getMaxActions(): number;
  setActions(actions: readonly PipTransportAction[]): Promise<void>;
  clearActions(): Promise<void>;
}

export type PipTransportSubscription = ReturnType<PipTransportNativeModule['addListener']>;

const nativeModule = requireOptionalNativeModule<PipTransportNativeModule>('MentionPipTransport');

/** Whether this build can put buttons in the OS window at all. */
export const isPipTransportAvailable = nativeModule !== null;

/**
 * The device's cap on PiP actions — three on most, but a runtime query, and `0`
 * both where the module is absent and where the device has no PiP.
 */
export function getMaxPipActions(): number {
  return nativeModule?.getMaxActions() ?? 0;
}

/** Publish the window's actions. Rejects if the activity cannot show them. */
export function setPipActions(actions: readonly PipTransportAction[]): Promise<void> {
  return nativeModule?.setActions(actions) ?? Promise.resolve();
}

/** Withdraw them again. */
export function clearPipActions(): Promise<void> {
  return nativeModule?.clearActions() ?? Promise.resolve();
}

/**
 * Listen for a press. `null` where the module is absent — there is nothing to
 * unsubscribe from, and inventing a no-op subscription would only hide that.
 */
export function addPipActionListener(
  listener: (event: PipTransportActionEvent) => void,
): PipTransportSubscription | null {
  return nativeModule?.addListener('onAction', listener) ?? null;
}
